DO $$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'm365risk') THEN
    CREATE ROLE m365risk LOGIN PASSWORD 'm365risk' NOBYPASSRLS;
  END IF;
END
$$;
GRANT CONNECT ON DATABASE m365risk TO m365risk;
GRANT USAGE, CREATE ON SCHEMA public TO m365risk;
