/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Alerts */
        get: operations["list_alerts_api_v1_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/alerts/{alert_id}/close": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Alert */
        post: operations["close_alert_api_v1_alerts__alert_id__close_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mock-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mock Token */
        post: operations["mock_token_api_v1_auth_mock_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Summary */
        get: operations["dashboard_summary_api_v1_dashboard_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/preflight": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Preflight Dataset */
        post: operations["preflight_dataset_api_v1_datasets_preflight_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/scanned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scanned Features
         * @description Page through stored V2 windows for a private, label-free training export.
         */
        get: operations["scanned_features_api_v1_datasets_scanned_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/datasets/scanned/subjects/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Scanned Subject Sample
         * @description Resolve a known local user to a sample ID for private analyst labelling.
         */
        get: operations["scanned_subject_sample_api_v1_datasets_scanned_subjects__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/mail/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent Mail Events
         * @description Return recent content-free mail telemetry for the verified tenant.
         */
        get: operations["recent_mail_events_api_v1_mail_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current Model */
        get: operations["current_model_api_v1_models_current_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Risks */
        get: operations["risks_api_v1_risks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/risks/{risk_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Feedback */
        post: operations["create_feedback_api_v1_risks__risk_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Simulation Runs */
        get: operations["list_simulation_runs_api_v1_simulation_runs_get"];
        put?: never;
        /** Create Simulation Run */
        post: operations["create_simulation_run_api_v1_simulation_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulation-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Simulation Run */
        get: operations["get_simulation_run_api_v1_simulation_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/faults/{fault}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulation Fault Start */
        post: operations["simulation_fault_start_api_v1_simulations_faults__fault__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulation Reset */
        post: operations["simulation_reset_api_v1_simulations_reset_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/scenarios/{scenario}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulation Start */
        post: operations["simulation_start_api_v1_simulations_scenarios__scenario__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Simulation Status */
        get: operations["simulation_status_api_v1_simulations_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/simulations/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Simulation Stop */
        post: operations["simulation_stop_api_v1_simulations_stop_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Sync */
        post: operations["start_sync_api_v1_sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/sync/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sync Jobs */
        get: operations["sync_jobs_api_v1_sync_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tenant Connection */
        get: operations["tenant_connection_api_v1_tenants_connection_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/onboarding/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Onboarding Callback */
        get: operations["onboarding_callback_api_v1_tenants_onboarding_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tenants/onboarding/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Onboarding Start */
        post: operations["onboarding_start_api_v1_tenants_onboarding_start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Users */
        get: operations["users_api_v1_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/risk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User Risk */
        get: operations["user_risk_api_v1_users__user_id__risk_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/risk-graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** User Risk Graph */
        get: operations["user_risk_graph_api_v1_users__user_id__risk_graph_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/risk-history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Risk History */
        get: operations["risk_history_api_v1_users__user_id__risk_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Live */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ready */
        get: operations["ready_health_ready_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics_metrics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AlertCloseRequest */
        AlertCloseRequest: {
            /**
             * Reason
             * @enum {string}
             */
            reason: "resolved" | "false_positive" | "accepted_risk";
        };
        /** AlertPage */
        AlertPage: {
            /** Items */
            items: components["schemas"]["AlertResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** AlertResponse */
        AlertResponse: {
            /** Closure */
            closure?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Provider Status */
            provider_status: string;
            /** Severity */
            severity: string;
            /** Soc Status */
            soc_status: string;
            /** User Id */
            user_id: string | null;
        };
        /** ConnectionResponse */
        ConnectionResponse: {
            /**
             * Mode
             * @enum {string}
             */
            mode: "mock" | "real";
            /** Provider */
            provider: string;
            /** Scopes */
            scopes: string[];
            /** Status */
            status: string;
            /** Updated At */
            updated_at?: string | null;
        };
        /** CursorPage */
        CursorPage: {
            /** Items */
            items: components["schemas"]["UserSummary"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** DashboardSummary */
        DashboardSummary: {
            /** Average Score */
            average_score: number;
            /** Critical */
            critical: number;
            /** High */
            high: number;
            /** Last Sync At */
            last_sync_at: string | null;
            /** Low */
            low: number;
            /** Medium */
            medium: number;
            /** Users */
            users: number;
        };
        /** DatasetPreflightRequest */
        DatasetPreflightRequest: {
            /** Columns */
            columns: string[];
            /**
             * Dataset Kind
             * @enum {string}
             */
            dataset_kind: "email" | "identity";
            /** Labelled */
            labelled: boolean;
            /**
             * Source Category
             * @enum {string}
             */
            source_category: "imported" | "generated" | "real_labelled";
        };
        /** DatasetPreflightResponse */
        DatasetPreflightResponse: {
            /** Compatible */
            compatible: boolean;
            /** Forbidden */
            forbidden: string[];
            /** Missing */
            missing: string[];
            /** Present */
            present: string[];
            /** Production Eligible */
            production_eligible: boolean;
            /** Source Category */
            source_category: string;
            /** Warnings */
            warnings: string[];
        };
        /** FeedbackCreate */
        FeedbackCreate: {
            /** Comment */
            comment?: string | null;
            /**
             * Verdict
             * @enum {string}
             */
            verdict: "true_positive" | "false_positive" | "safe";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** MailEventPage */
        MailEventPage: {
            /** Items */
            items: components["schemas"]["MailEventResponse"][];
        };
        /**
         * MailEventResponse
         * @description Privacy-safe header telemetry returned to the analyst dashboard.
         */
        MailEventResponse: {
            /** Authentication Results */
            authentication_results: {
                [key: string]: string;
            };
            /** External Sender */
            external_sender: boolean;
            /** From Sender Mismatch */
            from_sender_mismatch: boolean;
            /** Has Attachments */
            has_attachments: boolean;
            /** Id */
            id: string;
            /**
             * Importance
             * @enum {string}
             */
            importance: "low" | "normal" | "high";
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Received Hops */
            received_hops: number;
            /** Recipient Count */
            recipient_count: number;
            /** Reply To Domain Mismatch */
            reply_to_domain_mismatch: boolean;
            /** Risk Probability */
            risk_probability: number;
            /** Sender Domain Hash */
            sender_domain_hash: string;
            /** User Id */
            user_id: string;
        };
        /** ModelResponse */
        ModelResponse: {
            /** Approved */
            approved: boolean;
            /** Feature Version */
            feature_version: string;
            /** Metrics */
            metrics: {
                [key: string]: unknown;
            };
            /** Version */
            version: string;
        };
        /** RiskCursorPage */
        RiskCursorPage: {
            /** Items */
            items: components["schemas"]["RiskScoreResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** RiskFactorResponse */
        RiskFactorResponse: {
            /** Contribution */
            contribution: number;
            /** Name */
            name: string;
        };
        /** RiskGraphEdge */
        RiskGraphEdge: {
            /**
             * Relation
             * @enum {string}
             */
            relation: "HAS_OBSERVATION" | "DERIVES" | "CONTRIBUTES_TO";
            /** Source */
            source: string;
            /** Target */
            target: string;
        };
        /** RiskGraphNode */
        RiskGraphNode: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "employee" | "observation" | "feature" | "component";
            /** Label */
            label: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Observed At */
            observed_at?: string | null;
            /**
             * Status
             * @default available
             * @enum {string}
             */
            status: "available" | "unavailable" | "insufficient_history";
            /** Value */
            value?: number | string | boolean | null;
        };
        /** RiskScoreResponse */
        RiskScoreResponse: {
            /**
             * Calculated At
             * Format: date-time
             */
            calculated_at: string;
            /** Factors */
            factors: components["schemas"]["RiskFactorResponse"][];
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Level */
            level: string;
            /** Model Version */
            model_version: string;
            /** Recommended Actions */
            recommended_actions: string[];
            /** Score */
            score: number;
            /** User Id */
            user_id: string;
        };
        /** ScannedFeaturePage */
        ScannedFeaturePage: {
            /** Items */
            items: components["schemas"]["ScannedFeatureRow"][];
            /**
             * Labelled
             * @default false
             */
            labelled: boolean;
            /** Next Cursor */
            next_cursor?: string | null;
            /**
             * Source Category
             * @enum {string}
             */
            source_category: "generated" | "real_unlabelled";
        };
        /**
         * ScannedFeatureRow
         * @description Content-free, pseudonymous feature window for offline evaluation.
         */
        ScannedFeatureRow: {
            /** Availability */
            availability: {
                [key: string]: "available" | "unavailable" | "insufficient_history";
            };
            /** Components */
            components: {
                [key: string]: number | null;
            };
            /** Feature Version */
            feature_version: string;
            /** Features */
            features: {
                [key: string]: number | null;
            };
            /** Model Version */
            model_version: string;
            /** Sample Id */
            sample_id: string;
            /** Subject Key */
            subject_key: string;
            /**
             * Window End
             * Format: date-time
             */
            window_end: string;
        };
        /** SimulationFlowStage */
        SimulationFlowStage: {
            /** Detail */
            detail: string;
            /**
             * Key
             * @enum {string}
             */
            key: "injected" | "connector" | "synchronized" | "features" | "scored" | "alert";
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "active" | "done" | "failed";
        };
        /** SimulationRunCreate */
        SimulationRunCreate: {
            /**
             * Scenario
             * @enum {string}
             */
            scenario: "credential-phishing" | "domain-spoofing" | "executive-impersonation" | "account-takeover" | "mfa-removal" | "entra-escalation";
            /** Target User Id */
            target_user_id: string;
        };
        /** SimulationRunPage */
        SimulationRunPage: {
            /** Items */
            items: components["schemas"]["SimulationRunResponse"][];
        };
        /** SimulationRunResponse */
        SimulationRunResponse: {
            /** Baseline Score */
            baseline_score: number | null;
            /** Completed At */
            completed_at: string | null;
            /** Components */
            components: {
                [key: string]: number | null;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Score */
            current_score: number | null;
            /** Detected */
            detected: boolean;
            /** Expected Signal */
            expected_signal: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Measurements */
            measurements: {
                [key: string]: number | boolean | string | null;
            };
            /** Scenario */
            scenario: string;
            /** Score Delta */
            score_delta: number | null;
            /** Stages */
            stages: components["schemas"]["SimulationFlowStage"][];
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "syncing" | "evaluating" | "detected" | "missed" | "reset";
            /** Target Display Name */
            target_display_name: string;
            /** Target User Id */
            target_user_id: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** SimulationStatus */
        SimulationStatus: {
            /** Active */
            active: boolean;
            /** Generated Messages */
            generated_messages: number;
            /** Paused */
            paused: boolean;
            /** Scenario */
            scenario: string;
            /** Simulation Run Id */
            simulation_run_id?: string | null;
            /** Target User Id */
            target_user_id?: string | null;
        };
        /** SyncJobCursorPage */
        SyncJobCursorPage: {
            /** Items */
            items: components["schemas"]["SyncJobResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** SyncJobResponse */
        SyncJobResponse: {
            /** Attempt */
            attempt: number;
            /** Completed At */
            completed_at: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Error */
            error: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Next Attempt At
             * Format: date-time
             */
            next_attempt_at: string;
            /** Status */
            status: string;
        };
        /** TokenRequest */
        TokenRequest: {
            /**
             * Role
             * @default analyst
             * @enum {string}
             */
            role: "analyst" | "admin";
            /**
             * Tenant Id
             * Format: uuid
             */
            tenant_id: string;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserRiskGraphV2 */
        UserRiskGraphV2: {
            /**
             * Calculated At
             * Format: date-time
             */
            calculated_at: string;
            /** Components */
            components: {
                [key: string]: number | null;
            };
            /** Coverage */
            coverage: {
                [key: string]: "available" | "unavailable" | "insufficient_history";
            };
            /** Edges */
            edges: components["schemas"]["RiskGraphEdge"][];
            /** Feature Version */
            feature_version: string;
            /** Level */
            level: string;
            /** Model Version */
            model_version: string;
            /** Nodes */
            nodes: components["schemas"]["RiskGraphNode"][];
            /** Score */
            score: number | null;
            /** User Id */
            user_id: string;
        };
        /** UserSummary */
        UserSummary: {
            /** Calculated At */
            calculated_at?: string | null;
            /** Display Name */
            display_name: string;
            /** Entra Risk Level */
            entra_risk_level: string;
            /** Id */
            id: string;
            /** Is Admin */
            is_admin: boolean;
            /** Is Mfa Capable */
            is_mfa_capable: boolean;
            /** Is Mfa Registered */
            is_mfa_registered: boolean;
            /**
             * Level
             * @default low
             */
            level: string;
            /**
             * Score
             * @default 0
             */
            score: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_alerts_api_v1_alerts_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_alert_api_v1_alerts__alert_id__close_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertCloseRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mock_token_api_v1_auth_mock_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_summary_api_v1_dashboard_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardSummary"];
                };
            };
        };
    };
    preflight_dataset_api_v1_datasets_preflight_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DatasetPreflightRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatasetPreflightResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scanned_features_api_v1_datasets_scanned_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScannedFeaturePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scanned_subject_sample_api_v1_datasets_scanned_subjects__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScannedFeatureRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    recent_mail_events_api_v1_mail_events_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MailEventPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    current_model_api_v1_models_current_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelResponse"];
                };
            };
        };
    };
    risks_api_v1_risks_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskCursorPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_feedback_api_v1_risks__risk_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                risk_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_simulation_runs_api_v1_simulation_runs_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationRunPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_simulation_run_api_v1_simulation_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SimulationRunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_simulation_run_api_v1_simulation_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationRunResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulation_fault_start_api_v1_simulations_faults__fault__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                fault: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulation_reset_api_v1_simulations_reset_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationStatus"];
                };
            };
        };
    };
    simulation_start_api_v1_simulations_scenarios__scenario__start_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path: {
                scenario: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    simulation_status_api_v1_simulations_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationStatus"];
                };
            };
        };
    };
    simulation_stop_api_v1_simulations_stop_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulationStatus"];
                };
            };
        };
    };
    start_sync_api_v1_sync_post: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_jobs_api_v1_sync_jobs_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SyncJobCursorPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tenant_connection_api_v1_tenants_connection_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConnectionResponse"];
                };
            };
        };
    };
    onboarding_callback_api_v1_tenants_onboarding_callback_get: {
        parameters: {
            query: {
                tenant: string;
                state: string;
                admin_consent?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    onboarding_start_api_v1_tenants_onboarding_start_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    users_api_v1_users_get: {
        parameters: {
            query?: {
                level?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    user_risk_api_v1_users__user_id__risk_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskScoreResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    user_risk_graph_api_v1_users__user_id__risk_graph_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRiskGraphV2"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    risk_history_api_v1_users__user_id__risk_history_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskCursorPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    ready_health_ready_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    metrics_metrics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
